import { Router } from 'express';
import { requireAuth } from '../middleware/auth';
import * as ctrl from '../controllers/garudaCoreController';

const router = Router();
router.use(requireAuth);
router.get('/status', ctrl.status);
router.get('/revenue', ctrl.revenue);
router.get('/settlements', ctrl.settlements);
router.get('/income-goals', ctrl.incomeGoals);
router.post('/income-goals/preview', ctrl.previewMission);
router.post('/income-goals', ctrl.startMission);
router.get('/discovery/candidates', ctrl.discoveryCandidates);
router.patch('/discovery/candidates/:id/decision', ctrl.decideCandidate);
router.get('/work-intakes', ctrl.workIntakes);
router.post('/discovery/candidates/:id/work-intake/handoff', ctrl.prepareWorkIntakeHandoff);
router.post('/discovery/candidates/:id/work-intake/mission', ctrl.verifyWorkIntakeAndCreateMission);
router.get('/execution-missions', ctrl.executionMissions);
router.post('/discovery/candidates/:id/execution-mission', ctrl.createExecutionMission);
router.post('/execution-missions/:id/prepare', ctrl.prepareExecutionMission);
router.post('/execution-missions/:id/decision', ctrl.decideExecutionMission);
router.get('/execution-missions/:id/decisions', ctrl.executionMissionDecisions);
router.post('/execution-missions/:id/resubmit', ctrl.resubmitExecutionMission);
router.patch('/execution-missions/:id/tasks/:taskId', ctrl.transitionExecutionTask);
router.get('/execution-missions/:id/task-events', ctrl.executionTaskEvents);
router.post('/execution-missions/:id/auto-run', ctrl.runAutonomousExecutionTask);
router.post('/execution-missions/:id/auto-run-all', ctrl.runAutonomousExecutionMission);
router.get('/execution-missions/:id/task-runs', ctrl.autonomousTaskRuns);
router.get('/execution-missions/:id/action-requests', ctrl.externalActionRequests);
router.post('/execution-missions/:id/action-requests', ctrl.createExternalActionRequest);
router.post('/execution-missions/:id/action-requests/:requestId/decision', ctrl.decideExternalActionRequest);
router.post('/execution-missions/:id/action-requests/:requestId/completion', ctrl.completeExternalActionRequest);
router.get('/execution-missions/:id/mvp-readiness', ctrl.revenueMvpReadiness);
router.get('/revenue-connectors', ctrl.revenueConnectors);
router.post('/execution-missions/:id/action-requests/:requestId/dispatch', ctrl.dispatchExternalAction);
router.get('/execution-missions/:id/action-requests/:requestId/dispatches', ctrl.connectorDispatches);
router.get('/deployment-readiness', ctrl.deploymentReadiness);
router.get('/execution-missions/:id/pilot-ledger', ctrl.pilotLedger);
router.post('/execution-missions/:id/action-requests/:requestId/verified-earning', ctrl.recordVerifiedEarning);
router.get('/payments/razorpay-test/readiness', ctrl.razorpayTestReadiness);
router.post('/payments/razorpay-test/links', ctrl.prepareRazorpayTestLink);
router.get('/payments/account-readiness', ctrl.paymentAccountReadiness);
router.get('/execution-missions/:id/production-delivery', ctrl.productionDelivery);
router.post('/execution-missions/:id/production-delivery/quality', ctrl.recordProductionQuality);
router.post('/execution-missions/:id/production-delivery/final-approval', ctrl.approveFinalDelivery);
router.post('/execution-missions/:id/production-delivery/handoff', ctrl.prepareProductionDeliveryHandoff);
router.post('/execution-missions/:id/production-delivery/delivery-receipt', ctrl.recordProductionDeliveryReceipt);
router.post('/execution-missions/:id/production-delivery/client-acceptance', ctrl.recordProductionClientAcceptance);

export default router;
